#ifndef __ASKUA_TRAP_H__
#define __ASKUA_TRAP_H__

#define TF_RA (8)
#define TF_SP (TF_RA+8)
#define TF_GP (TF_SP+8)
#define TF_TP (TF_GP+8)
#define TF_T0 (TF_TP+8)
#define TF_T1 (TF_T0+8)
#define TF_T2 (TF_T1+8)
#define TF_S0 (TF_T2+8)
#define TF_S1 (TF_S0+8)
#define TF_A0 (TF_S1+8)
#define TF_A1 (TF_A0+8)
#define TF_A2 (TF_A1+8)
#define TF_A3 (TF_A2+8)
#define TF_A4 (TF_A3+8)
#define TF_A5 (TF_A4+8)
#define TF_A6 (TF_A5+8)
#define TF_A7 (TF_A6+8)
#define TF_S2 (TF_A7+8)
#define TF_S3 (TF_S2+8)
#define TF_S4 (TF_S3+8)
#define TF_S5 (TF_S4+8)
#define TF_S6 (TF_S5+8)
#define TF_S7 (TF_S6+8)
#define TF_S8 (TF_S7+8)
#define TF_S9 (TF_S8+8)
#define TF_S10 (TF_S9+8)
#define TF_S11 (TF_S10+8)
#define TF_T3 (TF_S11+8)
#define TF_T4 (TF_T3+8)
#define TF_T5 (TF_T4+8)
#define TF_T6 (TF_T5+8)
#define TF_KERNEL_SATP (TF_T6+8)
#define TF_TRAP_HANDLER (TF_KERNEL_SATP+8)
#define TF_EPC (TF_TRAP_HANDLER+8)
#define TF_HARTID (TF_EPC+8)
#define TF_KERNEL_SP (TF_HARTID+8)
#define TF_SIZE (TF_KERNEL_SP+8)

.macro SAVE_ALL
	sd ra, TF_RA(sp)
	sd gp, TF_GP(sp)
	sd tp, TF_TP(sp)
	sd t0, TF_T0(sp)
	sd t1, TF_T1(sp)
	sd t2, TF_T2(sp)
	sd s0, TF_S0(sp)
	sd s1, TF_S1(sp)
	sd a0, TF_A0(sp)
	sd a1, TF_A1(sp)
	sd a2, TF_A2(sp)
	sd a3, TF_A3(sp)
	sd a4, TF_A4(sp)
	sd a5, TF_A5(sp)
	sd a6, TF_A6(sp)
	sd a7, TF_A7(sp)
	sd s2, TF_S2(sp)
	sd s3, TF_S3(sp)
	sd s4, TF_S4(sp)
	sd s5, TF_S5(sp)
	sd s6, TF_S6(sp)
	sd s7, TF_S7(sp)
	sd s8, TF_S8(sp)
	sd s9, TF_S9(sp)
	sd s10, TF_S10(sp)
	sd s11, TF_S11(sp)
	sd t3, TF_T3(sp)
	sd t4, TF_T4(sp)
	sd t5, TF_T5(sp)
	sd t6, TF_T6(sp)
.endm

.macro RESTORE_ALL
	ld ra, TF_RA(sp)
	ld gp, TF_GP(sp)
	ld tp, TF_TP(sp)
	ld t0, TF_T0(sp)
	ld t1, TF_T1(sp)
	ld t2, TF_T2(sp)
	ld s0, TF_S0(sp)
	ld s1, TF_S1(sp)
	ld a0, TF_A0(sp)
	ld a1, TF_A1(sp)
	ld a2, TF_A2(sp)
	ld a3, TF_A3(sp)
	ld a4, TF_A4(sp)
	ld a5, TF_A5(sp)
	ld a6, TF_A6(sp)
	ld a7, TF_A7(sp)
	ld s2, TF_S2(sp)
	ld s3, TF_S3(sp)
	ld s4, TF_S4(sp)
	ld s5, TF_S5(sp)
	ld s6, TF_S6(sp)
	ld s7, TF_S7(sp)
	ld s8, TF_S8(sp)
	ld s9, TF_S9(sp)
	ld s10, TF_S10(sp)
	ld s11, TF_S11(sp)
	ld t3, TF_T3(sp)
	ld t4, TF_T4(sp)
	ld t5, TF_T5(sp)
	ld t6, TF_T6(sp)
.endm



#endif 