[build]
target = "cfg/rv64.json"

[target.rv64]
rustflags = ["-C","link-args=-Tlds/rv64.ld -z max-page-size=4096 -z nostart-stop-gc -Llib/target -lclib"]
# rustc-link-search = ["native=lib/target"]
# rustc-link-lib = ["static=clib"]
# rustc-cfg = [""]
# rustc-env = [""]


[target."cfg/aarch64.json"]
runner = "qemu-system-aarch64"
rustc-flags = []
rustc-link-search = [""]
rustc-link-lib = [""]
rustc-cfg = [""]
rustc-env = [""]



[unstable]
mtime-on-use = true
build-std = ["core", "alloc"]