[build]
target = "cfg/rv64.json"

[target."cfg/rv64.json"]
runner = "qemu-system-riscv64"
rustc-flags = ["-C", "link-arg=-Tlds/rv64.ld"]
rustc-link-search = [""]
rustc-link-lib = [""]
rustc-cfg = [""]
rustc-env = [""]


[target."cfg/aarch64.json"]
runner = "qemu-system-aarch64"
rustc-flags = ["-C", "link-arg=-Tlds/aarch64.ld"]
rustc-link-search = [""]
rustc-link-lib = [""]
rustc-cfg = [""]
rustc-env = [""]



[unstable]
mtime-on-use = true
build-std = ["core", "alloc"]