bitflags::bitflags! {
    pub struct Ext4FeatureCompat: u32 {
        const DIR_PREALLOC = EXT4_FEATURE_COMPAT_DIR_PREALLOC;
        const IMAGIC_INODES = EXT4_FEATURE_COMPAT_IMAGIC_INODES;
        const HAS_JOURNAL = EXT4_FEATURE_COMPAT_HAS_JOURNAL;
        const EXT_ATTR = EXT4_FEATURE_COMPAT_EXT_ATTR;
        const RESIZE_INODE = EXT4_FEATURE_COMPAT_RESIZE_INODE;
        const DIR_INDEX = EXT4_FEATURE_COMPAT_DIR_INDEX;
    }
    pub struct Ext4FeatureIncompat : u32 {
        const COMPRESSION = EXT4_FEATURE_INCOMPAT_COMPRESSION;
        const FILETYPE = EXT4_FEATURE_INCOMPAT_FILETYPE;
        const RECOVER = EXT4_FEATURE_INCOMPAT_RECOVER;
        const JOURNAL_DEV = EXT4_FEATURE_INCOMPAT_JOURNAL_DEV;
        const META_BG = EXT4_FEATURE_INCOMPAT_META_BG;
        const EXTENTS = EXT4_FEATURE_INCOMPAT_EXTENTS;
        const _64BIT = EXT4_FEATURE_INCOMPAT_64BIT;
        const MMP = EXT4_FEATURE_INCOMPAT_MMP;
        const FLEX_BG = EXT4_FEATURE_INCOMPAT_FLEX_BG;
        const EA_INODE = EXT4_FEATURE_INCOMPAT_EA_INODE;
        const DIRDATA = EXT4_FEATURE_INCOMPAT_DIRDATA;
        const CSUM_SEED = EXT4_FEATURE_INCOMPAT_CSUM_SEED;
    }
    pub struct Ext4FeatureRoCompat : u32 {
        const SPARSE_SUPER = EXT4_FEATURE_RO_COMPAT_SPARSE_SUPER;
        const LARGE_FILE = EXT4_FEATURE_RO_COMPAT_LARGE_FILE;
        const BTREE_DIR = EXT4_FEATURE_RO_COMPAT_BTREE_DIR;
        const HUGE_FILE = EXT4_FEATURE_RO_COMPAT_HUGE_FILE;
        const GDT_CSUM = EXT4_FEATURE_RO_COMPAT_GDT_CSUM;
        const DIR_NLINK = EXT4_FEATURE_RO_COMPAT_DIR_NLINK;
        const EXTRA_ISIZE = EXT4_FEATURE_RO_COMPAT_EXTRA_ISIZE;
    }
}

const EXT4_FEATURE_COMPAT_DIR_PREALLOC: u32 = 0x0001;
const EXT4_FEATURE_COMPAT_IMAGIC_INODES: u32 = 0x0002;
const EXT4_FEATURE_COMPAT_HAS_JOURNAL: u32 = 0x0004;
const EXT4_FEATURE_COMPAT_EXT_ATTR: u32 = 0x0008;
const EXT4_FEATURE_COMPAT_RESIZE_INODE: u32 = 0x0010;
const EXT4_FEATURE_COMPAT_DIR_INDEX: u32 = 0x0020;

const EXT4_FEATURE_RO_COMPAT_SPARSE_SUPER: u32 = 0x0001;
const EXT4_FEATURE_RO_COMPAT_LARGE_FILE: u32 = 0x0002;
const EXT4_FEATURE_RO_COMPAT_BTREE_DIR: u32 = 0x0004;
const EXT4_FEATURE_RO_COMPAT_HUGE_FILE: u32 = 0x0008;
const EXT4_FEATURE_RO_COMPAT_GDT_CSUM: u32 = 0x0010;
const EXT4_FEATURE_RO_COMPAT_DIR_NLINK: u32 = 0x0020;
const EXT4_FEATURE_RO_COMPAT_EXTRA_ISIZE: u32 = 0x0040;

const EXT4_FEATURE_INCOMPAT_COMPRESSION: u32 = 0x0001;
const EXT4_FEATURE_INCOMPAT_FILETYPE: u32 = 0x0002;
const EXT4_FEATURE_INCOMPAT_RECOVER: u32 = 0x0004;
const EXT4_FEATURE_INCOMPAT_JOURNAL_DEV: u32 = 0x0008;
const EXT4_FEATURE_INCOMPAT_META_BG: u32 = 0x0010;
const EXT4_FEATURE_INCOMPAT_EXTENTS: u32 = 0x0040;
const EXT4_FEATURE_INCOMPAT_64BIT: u32 = 0x0080;
const EXT4_FEATURE_INCOMPAT_MMP: u32 = 0x0100;
const EXT4_FEATURE_INCOMPAT_FLEX_BG: u32 = 0x0200;
const EXT4_FEATURE_INCOMPAT_EA_INODE: u32 = 0x0400;
const EXT4_FEATURE_INCOMPAT_DIRDATA: u32 = 0x1000;
const EXT4_FEATURE_INCOMPAT_CSUM_SEED: u32 = 0x2000;
